dist: xenial

language: php

php:
  - 7.4

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7
    packages:
      - mysql-server
      - mysql-client

sudo: required

before_script:
  - mysql -e 'create database t3;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --step

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 app/
